{% set name = "multiregex" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiregex-{{ version }}.tar.gz
  sha256: 0f52a148e1f793a7c7974eb06145db039bb64366bb6758b57899eab8d90f7355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
    - flit-core >=3.2,<4
  run:
    - pyahocorasick
    - python >=3.4

test:
  imports:
    - multiregex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quantco/multiregex
  summary: Speed up regex matching with non-regex substring "prematchers", similar to Bloom filters.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
    - jonashaag
